# Generated by Django 4.2.7 on 2023-11-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='conceot',
            new_name='concept',
        ),
    ]
