# Generated by Django 4.2.7 on 2023-11-09 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_durationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='durationtable',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 11, 9, 15, 45, 4, 313275)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='durationtable',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
