# Generated by Django 4.2.7 on 2023-11-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_durationtable_created_at_durationtable_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='durationtable',
            old_name='repeat_day',
            new_name='repeat_days',
        ),
    ]
